spring:
  application:
    name: Service1
  cloud:
    config:
      password: password.
      username: user
  config:
    import: configserver:http://localhost:8888
vaetech:
  load-balancer:
    instance1:
      enabledSSL: false
    instance2:
      enabledSSL: false