spring:
  application:
    name: Service1
  cloud:
    config:
      password: password.
      username: user
  config:
    import: configserver:http://localhost:8888
vaetech:
  load-balancer:
    instance1:
      protocol: http
      hostname: localhost
      #ports: [58579, 61940, 61941, 61942] # Los puertos lo obtiene de EurekaClient
    instance2:
      protocol: http
      hostname: localhost
      #ports: [59307] # Los puertos lo obtiene de EurekaClient